### ISSUE TITLE
Connection refused error heron-ui

### ISSUE THREAD

**Issue by naveenkumarmarri** [streamlio/heron-java-tutorial#2]
Hi
Thanks a lot for providing a great tutorial on heron.
I'm able to activate the topology. However when accessing the heron-ui
I'm getting 500 connection refused error.
following is the error log.

`[2017-08-28 10:42:15 +0000] [ERROR]: Uncaught exception GET /topologies (127.0.0.1)
HTTPServerRequest(protocol='http', host='localhost:8889', method='GET', uri='/topologies', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Accept-Language': 'en-US,en;q=0.8', 'Accept-Encoding': 'gzip, deflate, br', 'Host': 'localhost:8889', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36', 'Dnt': '1', 'Connection': 'keep-alive', 'Upgrade-Insecure-Requests': '1'})
Traceback (most recent call last):
  File "/home/tourist/.pex/install/tornado-4.0.2-py2.7-linux-x86_64.egg.ecdc759e18aea8131986e9909b5a56f2d0e41a19/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/web.py", line 1334, in _execute
    result = yield result
  File "/home/tourist/.pex/install/tornado-4.0.2-py2.7-linux-x86_64.egg.ecdc759e18aea8131986e9909b5a56f2d0e41a19/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/gen.py", line 628, in run
    value = future.result()
  File "/home/tourist/.pex/install/tornado-4.0.2-py2.7-linux-x86_64.egg.ecdc759e18aea8131986e9909b5a56f2d0e41a19/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/concurrent.py", line 109, in result
    raise_exc_info(self._exc_info)
  File "/home/tourist/.pex/install/tornado-4.0.2-py2.7-linux-x86_64.egg.ecdc759e18aea8131986e9909b5a56f2d0e41a19/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/gen.py", line 631, in run
    yielded = self.gen.throw(*sys.exc_info())
  File "/home/tourist/bin/heron-ui/heron/tools/ui/src/python/handlers/topology.py", line 96, in get
    clusters = yield access.get_clusters()
  File "/home/tourist/.pex/install/tornado-4.0.2-py2.7-linux-x86_64.egg.ecdc759e18aea8131986e9909b5a56f2d0e41a19/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/gen.py", line 628, in run
    value = future.result()
  File "/home/tourist/.pex/install/tornado-4.0.2-py2.7-linux-x86_64.egg.ecdc759e18aea8131986e9909b5a56f2d0e41a19/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/concurrent.py", line 109, in result
    raise_exc_info(self._exc_info)
  File "/home/tourist/.pex/install/tornado-4.0.2-py2.7-linux-x86_64.egg.ecdc759e18aea8131986e9909b5a56f2d0e41a19/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/gen.py", line 631, in run
    yielded = self.gen.throw(*sys.exc_info())
  File "/home/tourist/bin/heron-ui/heron/tools/common/src/python/access/heron_api.py", line 113, in get_clusters
    raise tornado.gen.Return((yield fetch_url_as_json(request_url)))
  File "/home/tourist/.pex/install/tornado-4.0.2-py2.7-linux-x86_64.egg.ecdc759e18aea8131986e9909b5a56f2d0e41a19/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/gen.py", line 628, in run
    value = future.result()
  File "/home/tourist/.pex/install/tornado-4.0.2-py2.7-linux-x86_64.egg.ecdc759e18aea8131986e9909b5a56f2d0e41a19/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/concurrent.py", line 109, in result
    raise_exc_info(self._exc_info)
  File "/home/tourist/.pex/install/tornado-4.0.2-py2.7-linux-x86_64.egg.ecdc759e18aea8131986e9909b5a56f2d0e41a19/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/gen.py", line 631, in run
    yielded = self.gen.throw(*sys.exc_info())
  File "/home/tourist/bin/heron-ui/heron/tools/common/src/python/access/fetch.py", line 47, in fetch_url_as_json
    http_response = yield tornado.httpclient.AsyncHTTPClient().fetch(fetch_url)
  File "/home/tourist/.pex/install/tornado-4.0.2-py2.7-linux-x86_64.egg.ecdc759e18aea8131986e9909b5a56f2d0e41a19/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/gen.py", line 628, in run
    value = future.result()
  File "/home/tourist/.pex/install/tornado-4.0.2-py2.7-linux-x86_64.egg.ecdc759e18aea8131986e9909b5a56f2d0e41a19/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/concurrent.py", line 111, in result
    raise self._exception
error: [Errno 111] Connection refused
`

can you please help me on this?

**Comment by aahmed-se** [comment]
Which env are you running this in ?

**Comment by naveenkumarmarri** [comment]
Ubuntu 16.04

**Comment by aahmed-se** [comment]
what's the heron version you are using ?

**Comment by naveenkumarmarri** [comment]
0.15.0

**Comment by aahmed-se** [comment]
that should be fine , can you confirm that the heron tracker is running normally ?

**Comment by srkukarni** [comment]
@naveenkumarmarri Were you able to figure out what the issue was?

**Comment by naveenkumarmarri** [comment]
@srkukarni yes there was some issue with my ip
Fixed it. thanks a lot :+1:
